/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ebay.epic.soj.common.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ClavSession extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6730295609054705353L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ClavSession\",\"namespace\":\"com.ebay.epic.soj.common.model\",\"fields\":[{\"name\":\"session_skey\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"site_id\",\"type\":\"int\"},{\"name\":\"botFlag\",\"type\":\"boolean\"},{\"name\":\"valid_page_count\",\"type\":\"int\"},{\"name\":\"duration\",\"type\":\"long\"},{\"name\":\"start_page_id\",\"type\":\"int\"},{\"name\":\"exit_page_id\",\"type\":\"int\"},{\"name\":\"start_timestamp\",\"type\":\"long\"},{\"name\":\"exit_timestamp\",\"type\":\"long\"},{\"name\":\"gr_count\",\"type\":\"int\"},{\"name\":\"gr1_count\",\"type\":\"int\"},{\"name\":\"homepage_count\",\"type\":\"int\"},{\"name\":\"vi_count\",\"type\":\"int\"},{\"name\":\"signin_count\",\"type\":\"int\"},{\"name\":\"myebay_count\",\"type\":\"int\"},{\"name\":\"others\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ClavSession> ENCODER =
      new BinaryMessageEncoder<ClavSession>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ClavSession> DECODER =
      new BinaryMessageDecoder<ClavSession>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ClavSession> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ClavSession> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ClavSession>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ClavSession to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ClavSession from a ByteBuffer. */
  public static ClavSession fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String session_skey;
  @Deprecated public int site_id;
  @Deprecated public boolean botFlag;
  @Deprecated public int valid_page_count;
  @Deprecated public long duration;
  @Deprecated public int start_page_id;
  @Deprecated public int exit_page_id;
  @Deprecated public long start_timestamp;
  @Deprecated public long exit_timestamp;
  @Deprecated public int gr_count;
  @Deprecated public int gr1_count;
  @Deprecated public int homepage_count;
  @Deprecated public int vi_count;
  @Deprecated public int signin_count;
  @Deprecated public int myebay_count;
  @Deprecated public java.util.Map<java.lang.String,java.lang.String> others;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ClavSession() {}

  /**
   * All-args constructor.
   * @param session_skey The new value for session_skey
   * @param site_id The new value for site_id
   * @param botFlag The new value for botFlag
   * @param valid_page_count The new value for valid_page_count
   * @param duration The new value for duration
   * @param start_page_id The new value for start_page_id
   * @param exit_page_id The new value for exit_page_id
   * @param start_timestamp The new value for start_timestamp
   * @param exit_timestamp The new value for exit_timestamp
   * @param gr_count The new value for gr_count
   * @param gr1_count The new value for gr1_count
   * @param homepage_count The new value for homepage_count
   * @param vi_count The new value for vi_count
   * @param signin_count The new value for signin_count
   * @param myebay_count The new value for myebay_count
   * @param others The new value for others
   */
  public ClavSession(java.lang.String session_skey, java.lang.Integer site_id, java.lang.Boolean botFlag, java.lang.Integer valid_page_count, java.lang.Long duration, java.lang.Integer start_page_id, java.lang.Integer exit_page_id, java.lang.Long start_timestamp, java.lang.Long exit_timestamp, java.lang.Integer gr_count, java.lang.Integer gr1_count, java.lang.Integer homepage_count, java.lang.Integer vi_count, java.lang.Integer signin_count, java.lang.Integer myebay_count, java.util.Map<java.lang.String,java.lang.String> others) {
    this.session_skey = session_skey;
    this.site_id = site_id;
    this.botFlag = botFlag;
    this.valid_page_count = valid_page_count;
    this.duration = duration;
    this.start_page_id = start_page_id;
    this.exit_page_id = exit_page_id;
    this.start_timestamp = start_timestamp;
    this.exit_timestamp = exit_timestamp;
    this.gr_count = gr_count;
    this.gr1_count = gr1_count;
    this.homepage_count = homepage_count;
    this.vi_count = vi_count;
    this.signin_count = signin_count;
    this.myebay_count = myebay_count;
    this.others = others;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return session_skey;
    case 1: return site_id;
    case 2: return botFlag;
    case 3: return valid_page_count;
    case 4: return duration;
    case 5: return start_page_id;
    case 6: return exit_page_id;
    case 7: return start_timestamp;
    case 8: return exit_timestamp;
    case 9: return gr_count;
    case 10: return gr1_count;
    case 11: return homepage_count;
    case 12: return vi_count;
    case 13: return signin_count;
    case 14: return myebay_count;
    case 15: return others;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: session_skey = (java.lang.String)value$; break;
    case 1: site_id = (java.lang.Integer)value$; break;
    case 2: botFlag = (java.lang.Boolean)value$; break;
    case 3: valid_page_count = (java.lang.Integer)value$; break;
    case 4: duration = (java.lang.Long)value$; break;
    case 5: start_page_id = (java.lang.Integer)value$; break;
    case 6: exit_page_id = (java.lang.Integer)value$; break;
    case 7: start_timestamp = (java.lang.Long)value$; break;
    case 8: exit_timestamp = (java.lang.Long)value$; break;
    case 9: gr_count = (java.lang.Integer)value$; break;
    case 10: gr1_count = (java.lang.Integer)value$; break;
    case 11: homepage_count = (java.lang.Integer)value$; break;
    case 12: vi_count = (java.lang.Integer)value$; break;
    case 13: signin_count = (java.lang.Integer)value$; break;
    case 14: myebay_count = (java.lang.Integer)value$; break;
    case 15: others = (java.util.Map<java.lang.String,java.lang.String>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'session_skey' field.
   * @return The value of the 'session_skey' field.
   */
  public java.lang.String getSessionSkey() {
    return session_skey;
  }

  /**
   * Sets the value of the 'session_skey' field.
   * @param value the value to set.
   */
  public void setSessionSkey(java.lang.String value) {
    this.session_skey = value;
  }

  /**
   * Gets the value of the 'site_id' field.
   * @return The value of the 'site_id' field.
   */
  public java.lang.Integer getSiteId() {
    return site_id;
  }

  /**
   * Sets the value of the 'site_id' field.
   * @param value the value to set.
   */
  public void setSiteId(java.lang.Integer value) {
    this.site_id = value;
  }

  /**
   * Gets the value of the 'botFlag' field.
   * @return The value of the 'botFlag' field.
   */
  public java.lang.Boolean getBotFlag() {
    return botFlag;
  }

  /**
   * Sets the value of the 'botFlag' field.
   * @param value the value to set.
   */
  public void setBotFlag(java.lang.Boolean value) {
    this.botFlag = value;
  }

  /**
   * Gets the value of the 'valid_page_count' field.
   * @return The value of the 'valid_page_count' field.
   */
  public java.lang.Integer getValidPageCount() {
    return valid_page_count;
  }

  /**
   * Sets the value of the 'valid_page_count' field.
   * @param value the value to set.
   */
  public void setValidPageCount(java.lang.Integer value) {
    this.valid_page_count = value;
  }

  /**
   * Gets the value of the 'duration' field.
   * @return The value of the 'duration' field.
   */
  public java.lang.Long getDuration() {
    return duration;
  }

  /**
   * Sets the value of the 'duration' field.
   * @param value the value to set.
   */
  public void setDuration(java.lang.Long value) {
    this.duration = value;
  }

  /**
   * Gets the value of the 'start_page_id' field.
   * @return The value of the 'start_page_id' field.
   */
  public java.lang.Integer getStartPageId() {
    return start_page_id;
  }

  /**
   * Sets the value of the 'start_page_id' field.
   * @param value the value to set.
   */
  public void setStartPageId(java.lang.Integer value) {
    this.start_page_id = value;
  }

  /**
   * Gets the value of the 'exit_page_id' field.
   * @return The value of the 'exit_page_id' field.
   */
  public java.lang.Integer getExitPageId() {
    return exit_page_id;
  }

  /**
   * Sets the value of the 'exit_page_id' field.
   * @param value the value to set.
   */
  public void setExitPageId(java.lang.Integer value) {
    this.exit_page_id = value;
  }

  /**
   * Gets the value of the 'start_timestamp' field.
   * @return The value of the 'start_timestamp' field.
   */
  public java.lang.Long getStartTimestamp() {
    return start_timestamp;
  }

  /**
   * Sets the value of the 'start_timestamp' field.
   * @param value the value to set.
   */
  public void setStartTimestamp(java.lang.Long value) {
    this.start_timestamp = value;
  }

  /**
   * Gets the value of the 'exit_timestamp' field.
   * @return The value of the 'exit_timestamp' field.
   */
  public java.lang.Long getExitTimestamp() {
    return exit_timestamp;
  }

  /**
   * Sets the value of the 'exit_timestamp' field.
   * @param value the value to set.
   */
  public void setExitTimestamp(java.lang.Long value) {
    this.exit_timestamp = value;
  }

  /**
   * Gets the value of the 'gr_count' field.
   * @return The value of the 'gr_count' field.
   */
  public java.lang.Integer getGrCount() {
    return gr_count;
  }

  /**
   * Sets the value of the 'gr_count' field.
   * @param value the value to set.
   */
  public void setGrCount(java.lang.Integer value) {
    this.gr_count = value;
  }

  /**
   * Gets the value of the 'gr1_count' field.
   * @return The value of the 'gr1_count' field.
   */
  public java.lang.Integer getGr1Count() {
    return gr1_count;
  }

  /**
   * Sets the value of the 'gr1_count' field.
   * @param value the value to set.
   */
  public void setGr1Count(java.lang.Integer value) {
    this.gr1_count = value;
  }

  /**
   * Gets the value of the 'homepage_count' field.
   * @return The value of the 'homepage_count' field.
   */
  public java.lang.Integer getHomepageCount() {
    return homepage_count;
  }

  /**
   * Sets the value of the 'homepage_count' field.
   * @param value the value to set.
   */
  public void setHomepageCount(java.lang.Integer value) {
    this.homepage_count = value;
  }

  /**
   * Gets the value of the 'vi_count' field.
   * @return The value of the 'vi_count' field.
   */
  public java.lang.Integer getViCount() {
    return vi_count;
  }

  /**
   * Sets the value of the 'vi_count' field.
   * @param value the value to set.
   */
  public void setViCount(java.lang.Integer value) {
    this.vi_count = value;
  }

  /**
   * Gets the value of the 'signin_count' field.
   * @return The value of the 'signin_count' field.
   */
  public java.lang.Integer getSigninCount() {
    return signin_count;
  }

  /**
   * Sets the value of the 'signin_count' field.
   * @param value the value to set.
   */
  public void setSigninCount(java.lang.Integer value) {
    this.signin_count = value;
  }

  /**
   * Gets the value of the 'myebay_count' field.
   * @return The value of the 'myebay_count' field.
   */
  public java.lang.Integer getMyebayCount() {
    return myebay_count;
  }

  /**
   * Sets the value of the 'myebay_count' field.
   * @param value the value to set.
   */
  public void setMyebayCount(java.lang.Integer value) {
    this.myebay_count = value;
  }

  /**
   * Gets the value of the 'others' field.
   * @return The value of the 'others' field.
   */
  public java.util.Map<java.lang.String,java.lang.String> getOthers() {
    return others;
  }

  /**
   * Sets the value of the 'others' field.
   * @param value the value to set.
   */
  public void setOthers(java.util.Map<java.lang.String,java.lang.String> value) {
    this.others = value;
  }

  /**
   * Creates a new ClavSession RecordBuilder.
   * @return A new ClavSession RecordBuilder
   */
  public static com.ebay.epic.soj.common.model.ClavSession.Builder newBuilder() {
    return new com.ebay.epic.soj.common.model.ClavSession.Builder();
  }

  /**
   * Creates a new ClavSession RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ClavSession RecordBuilder
   */
  public static com.ebay.epic.soj.common.model.ClavSession.Builder newBuilder(com.ebay.epic.soj.common.model.ClavSession.Builder other) {
    return new com.ebay.epic.soj.common.model.ClavSession.Builder(other);
  }

  /**
   * Creates a new ClavSession RecordBuilder by copying an existing ClavSession instance.
   * @param other The existing instance to copy.
   * @return A new ClavSession RecordBuilder
   */
  public static com.ebay.epic.soj.common.model.ClavSession.Builder newBuilder(com.ebay.epic.soj.common.model.ClavSession other) {
    return new com.ebay.epic.soj.common.model.ClavSession.Builder(other);
  }

  /**
   * RecordBuilder for ClavSession instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ClavSession>
    implements org.apache.avro.data.RecordBuilder<ClavSession> {

    private java.lang.String session_skey;
    private int site_id;
    private boolean botFlag;
    private int valid_page_count;
    private long duration;
    private int start_page_id;
    private int exit_page_id;
    private long start_timestamp;
    private long exit_timestamp;
    private int gr_count;
    private int gr1_count;
    private int homepage_count;
    private int vi_count;
    private int signin_count;
    private int myebay_count;
    private java.util.Map<java.lang.String,java.lang.String> others;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ebay.epic.soj.common.model.ClavSession.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.session_skey)) {
        this.session_skey = data().deepCopy(fields()[0].schema(), other.session_skey);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.site_id)) {
        this.site_id = data().deepCopy(fields()[1].schema(), other.site_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.botFlag)) {
        this.botFlag = data().deepCopy(fields()[2].schema(), other.botFlag);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.valid_page_count)) {
        this.valid_page_count = data().deepCopy(fields()[3].schema(), other.valid_page_count);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.duration)) {
        this.duration = data().deepCopy(fields()[4].schema(), other.duration);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.start_page_id)) {
        this.start_page_id = data().deepCopy(fields()[5].schema(), other.start_page_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.exit_page_id)) {
        this.exit_page_id = data().deepCopy(fields()[6].schema(), other.exit_page_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.start_timestamp)) {
        this.start_timestamp = data().deepCopy(fields()[7].schema(), other.start_timestamp);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.exit_timestamp)) {
        this.exit_timestamp = data().deepCopy(fields()[8].schema(), other.exit_timestamp);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.gr_count)) {
        this.gr_count = data().deepCopy(fields()[9].schema(), other.gr_count);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.gr1_count)) {
        this.gr1_count = data().deepCopy(fields()[10].schema(), other.gr1_count);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.homepage_count)) {
        this.homepage_count = data().deepCopy(fields()[11].schema(), other.homepage_count);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.vi_count)) {
        this.vi_count = data().deepCopy(fields()[12].schema(), other.vi_count);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.signin_count)) {
        this.signin_count = data().deepCopy(fields()[13].schema(), other.signin_count);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.myebay_count)) {
        this.myebay_count = data().deepCopy(fields()[14].schema(), other.myebay_count);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.others)) {
        this.others = data().deepCopy(fields()[15].schema(), other.others);
        fieldSetFlags()[15] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ClavSession instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ebay.epic.soj.common.model.ClavSession other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.session_skey)) {
        this.session_skey = data().deepCopy(fields()[0].schema(), other.session_skey);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.site_id)) {
        this.site_id = data().deepCopy(fields()[1].schema(), other.site_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.botFlag)) {
        this.botFlag = data().deepCopy(fields()[2].schema(), other.botFlag);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.valid_page_count)) {
        this.valid_page_count = data().deepCopy(fields()[3].schema(), other.valid_page_count);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.duration)) {
        this.duration = data().deepCopy(fields()[4].schema(), other.duration);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.start_page_id)) {
        this.start_page_id = data().deepCopy(fields()[5].schema(), other.start_page_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.exit_page_id)) {
        this.exit_page_id = data().deepCopy(fields()[6].schema(), other.exit_page_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.start_timestamp)) {
        this.start_timestamp = data().deepCopy(fields()[7].schema(), other.start_timestamp);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.exit_timestamp)) {
        this.exit_timestamp = data().deepCopy(fields()[8].schema(), other.exit_timestamp);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.gr_count)) {
        this.gr_count = data().deepCopy(fields()[9].schema(), other.gr_count);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.gr1_count)) {
        this.gr1_count = data().deepCopy(fields()[10].schema(), other.gr1_count);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.homepage_count)) {
        this.homepage_count = data().deepCopy(fields()[11].schema(), other.homepage_count);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.vi_count)) {
        this.vi_count = data().deepCopy(fields()[12].schema(), other.vi_count);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.signin_count)) {
        this.signin_count = data().deepCopy(fields()[13].schema(), other.signin_count);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.myebay_count)) {
        this.myebay_count = data().deepCopy(fields()[14].schema(), other.myebay_count);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.others)) {
        this.others = data().deepCopy(fields()[15].schema(), other.others);
        fieldSetFlags()[15] = true;
      }
    }

    /**
      * Gets the value of the 'session_skey' field.
      * @return The value.
      */
    public java.lang.String getSessionSkey() {
      return session_skey;
    }

    /**
      * Sets the value of the 'session_skey' field.
      * @param value The value of 'session_skey'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setSessionSkey(java.lang.String value) {
      validate(fields()[0], value);
      this.session_skey = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'session_skey' field has been set.
      * @return True if the 'session_skey' field has been set, false otherwise.
      */
    public boolean hasSessionSkey() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'session_skey' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearSessionSkey() {
      session_skey = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'site_id' field.
      * @return The value.
      */
    public java.lang.Integer getSiteId() {
      return site_id;
    }

    /**
      * Sets the value of the 'site_id' field.
      * @param value The value of 'site_id'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setSiteId(int value) {
      validate(fields()[1], value);
      this.site_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'site_id' field has been set.
      * @return True if the 'site_id' field has been set, false otherwise.
      */
    public boolean hasSiteId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'site_id' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearSiteId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'botFlag' field.
      * @return The value.
      */
    public java.lang.Boolean getBotFlag() {
      return botFlag;
    }

    /**
      * Sets the value of the 'botFlag' field.
      * @param value The value of 'botFlag'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setBotFlag(boolean value) {
      validate(fields()[2], value);
      this.botFlag = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'botFlag' field has been set.
      * @return True if the 'botFlag' field has been set, false otherwise.
      */
    public boolean hasBotFlag() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'botFlag' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearBotFlag() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'valid_page_count' field.
      * @return The value.
      */
    public java.lang.Integer getValidPageCount() {
      return valid_page_count;
    }

    /**
      * Sets the value of the 'valid_page_count' field.
      * @param value The value of 'valid_page_count'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setValidPageCount(int value) {
      validate(fields()[3], value);
      this.valid_page_count = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'valid_page_count' field has been set.
      * @return True if the 'valid_page_count' field has been set, false otherwise.
      */
    public boolean hasValidPageCount() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'valid_page_count' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearValidPageCount() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'duration' field.
      * @return The value.
      */
    public java.lang.Long getDuration() {
      return duration;
    }

    /**
      * Sets the value of the 'duration' field.
      * @param value The value of 'duration'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setDuration(long value) {
      validate(fields()[4], value);
      this.duration = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'duration' field has been set.
      * @return True if the 'duration' field has been set, false otherwise.
      */
    public boolean hasDuration() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'duration' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearDuration() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'start_page_id' field.
      * @return The value.
      */
    public java.lang.Integer getStartPageId() {
      return start_page_id;
    }

    /**
      * Sets the value of the 'start_page_id' field.
      * @param value The value of 'start_page_id'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setStartPageId(int value) {
      validate(fields()[5], value);
      this.start_page_id = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'start_page_id' field has been set.
      * @return True if the 'start_page_id' field has been set, false otherwise.
      */
    public boolean hasStartPageId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'start_page_id' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearStartPageId() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'exit_page_id' field.
      * @return The value.
      */
    public java.lang.Integer getExitPageId() {
      return exit_page_id;
    }

    /**
      * Sets the value of the 'exit_page_id' field.
      * @param value The value of 'exit_page_id'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setExitPageId(int value) {
      validate(fields()[6], value);
      this.exit_page_id = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'exit_page_id' field has been set.
      * @return True if the 'exit_page_id' field has been set, false otherwise.
      */
    public boolean hasExitPageId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'exit_page_id' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearExitPageId() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'start_timestamp' field.
      * @return The value.
      */
    public java.lang.Long getStartTimestamp() {
      return start_timestamp;
    }

    /**
      * Sets the value of the 'start_timestamp' field.
      * @param value The value of 'start_timestamp'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setStartTimestamp(long value) {
      validate(fields()[7], value);
      this.start_timestamp = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'start_timestamp' field has been set.
      * @return True if the 'start_timestamp' field has been set, false otherwise.
      */
    public boolean hasStartTimestamp() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'start_timestamp' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearStartTimestamp() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'exit_timestamp' field.
      * @return The value.
      */
    public java.lang.Long getExitTimestamp() {
      return exit_timestamp;
    }

    /**
      * Sets the value of the 'exit_timestamp' field.
      * @param value The value of 'exit_timestamp'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setExitTimestamp(long value) {
      validate(fields()[8], value);
      this.exit_timestamp = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'exit_timestamp' field has been set.
      * @return True if the 'exit_timestamp' field has been set, false otherwise.
      */
    public boolean hasExitTimestamp() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'exit_timestamp' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearExitTimestamp() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'gr_count' field.
      * @return The value.
      */
    public java.lang.Integer getGrCount() {
      return gr_count;
    }

    /**
      * Sets the value of the 'gr_count' field.
      * @param value The value of 'gr_count'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setGrCount(int value) {
      validate(fields()[9], value);
      this.gr_count = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'gr_count' field has been set.
      * @return True if the 'gr_count' field has been set, false otherwise.
      */
    public boolean hasGrCount() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'gr_count' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearGrCount() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'gr1_count' field.
      * @return The value.
      */
    public java.lang.Integer getGr1Count() {
      return gr1_count;
    }

    /**
      * Sets the value of the 'gr1_count' field.
      * @param value The value of 'gr1_count'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setGr1Count(int value) {
      validate(fields()[10], value);
      this.gr1_count = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'gr1_count' field has been set.
      * @return True if the 'gr1_count' field has been set, false otherwise.
      */
    public boolean hasGr1Count() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'gr1_count' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearGr1Count() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'homepage_count' field.
      * @return The value.
      */
    public java.lang.Integer getHomepageCount() {
      return homepage_count;
    }

    /**
      * Sets the value of the 'homepage_count' field.
      * @param value The value of 'homepage_count'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setHomepageCount(int value) {
      validate(fields()[11], value);
      this.homepage_count = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'homepage_count' field has been set.
      * @return True if the 'homepage_count' field has been set, false otherwise.
      */
    public boolean hasHomepageCount() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'homepage_count' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearHomepageCount() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'vi_count' field.
      * @return The value.
      */
    public java.lang.Integer getViCount() {
      return vi_count;
    }

    /**
      * Sets the value of the 'vi_count' field.
      * @param value The value of 'vi_count'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setViCount(int value) {
      validate(fields()[12], value);
      this.vi_count = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'vi_count' field has been set.
      * @return True if the 'vi_count' field has been set, false otherwise.
      */
    public boolean hasViCount() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'vi_count' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearViCount() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'signin_count' field.
      * @return The value.
      */
    public java.lang.Integer getSigninCount() {
      return signin_count;
    }

    /**
      * Sets the value of the 'signin_count' field.
      * @param value The value of 'signin_count'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setSigninCount(int value) {
      validate(fields()[13], value);
      this.signin_count = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'signin_count' field has been set.
      * @return True if the 'signin_count' field has been set, false otherwise.
      */
    public boolean hasSigninCount() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'signin_count' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearSigninCount() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'myebay_count' field.
      * @return The value.
      */
    public java.lang.Integer getMyebayCount() {
      return myebay_count;
    }

    /**
      * Sets the value of the 'myebay_count' field.
      * @param value The value of 'myebay_count'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setMyebayCount(int value) {
      validate(fields()[14], value);
      this.myebay_count = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'myebay_count' field has been set.
      * @return True if the 'myebay_count' field has been set, false otherwise.
      */
    public boolean hasMyebayCount() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'myebay_count' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearMyebayCount() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'others' field.
      * @return The value.
      */
    public java.util.Map<java.lang.String,java.lang.String> getOthers() {
      return others;
    }

    /**
      * Sets the value of the 'others' field.
      * @param value The value of 'others'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setOthers(java.util.Map<java.lang.String,java.lang.String> value) {
      validate(fields()[15], value);
      this.others = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'others' field has been set.
      * @return True if the 'others' field has been set, false otherwise.
      */
    public boolean hasOthers() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'others' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearOthers() {
      others = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ClavSession build() {
      try {
        ClavSession record = new ClavSession();
        record.session_skey = fieldSetFlags()[0] ? this.session_skey : (java.lang.String) defaultValue(fields()[0]);
        record.site_id = fieldSetFlags()[1] ? this.site_id : (java.lang.Integer) defaultValue(fields()[1]);
        record.botFlag = fieldSetFlags()[2] ? this.botFlag : (java.lang.Boolean) defaultValue(fields()[2]);
        record.valid_page_count = fieldSetFlags()[3] ? this.valid_page_count : (java.lang.Integer) defaultValue(fields()[3]);
        record.duration = fieldSetFlags()[4] ? this.duration : (java.lang.Long) defaultValue(fields()[4]);
        record.start_page_id = fieldSetFlags()[5] ? this.start_page_id : (java.lang.Integer) defaultValue(fields()[5]);
        record.exit_page_id = fieldSetFlags()[6] ? this.exit_page_id : (java.lang.Integer) defaultValue(fields()[6]);
        record.start_timestamp = fieldSetFlags()[7] ? this.start_timestamp : (java.lang.Long) defaultValue(fields()[7]);
        record.exit_timestamp = fieldSetFlags()[8] ? this.exit_timestamp : (java.lang.Long) defaultValue(fields()[8]);
        record.gr_count = fieldSetFlags()[9] ? this.gr_count : (java.lang.Integer) defaultValue(fields()[9]);
        record.gr1_count = fieldSetFlags()[10] ? this.gr1_count : (java.lang.Integer) defaultValue(fields()[10]);
        record.homepage_count = fieldSetFlags()[11] ? this.homepage_count : (java.lang.Integer) defaultValue(fields()[11]);
        record.vi_count = fieldSetFlags()[12] ? this.vi_count : (java.lang.Integer) defaultValue(fields()[12]);
        record.signin_count = fieldSetFlags()[13] ? this.signin_count : (java.lang.Integer) defaultValue(fields()[13]);
        record.myebay_count = fieldSetFlags()[14] ? this.myebay_count : (java.lang.Integer) defaultValue(fields()[14]);
        record.others = fieldSetFlags()[15] ? this.others : (java.util.Map<java.lang.String,java.lang.String>) defaultValue(fields()[15]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ClavSession>
    WRITER$ = (org.apache.avro.io.DatumWriter<ClavSession>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ClavSession>
    READER$ = (org.apache.avro.io.DatumReader<ClavSession>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
