/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ebay.epic.soj.common.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ClavSession extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1152536039928496387L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ClavSession\",\"namespace\":\"com.ebay.epic.soj.common.model\",\"fields\":[{\"name\":\"sessionId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"siteId\",\"type\":\"int\"},{\"name\":\"botFlag\",\"type\":\"long\"},{\"name\":\"validPageCount\",\"type\":\"int\"},{\"name\":\"duration\",\"type\":\"long\"},{\"name\":\"startPageId\",\"type\":\"int\"},{\"name\":\"exitPageId\",\"type\":\"int\"},{\"name\":\"startTimestamp\",\"type\":\"long\"},{\"name\":\"exitTimestamp\",\"type\":\"long\"},{\"name\":\"grCount\",\"type\":\"int\"},{\"name\":\"gr1Count\",\"type\":\"int\"},{\"name\":\"homepageCount\",\"type\":\"int\"},{\"name\":\"viCount\",\"type\":\"int\"},{\"name\":\"signinCount\",\"type\":\"int\"},{\"name\":\"myebayCount\",\"type\":\"int\"},{\"name\":\"others\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ClavSession> ENCODER =
      new BinaryMessageEncoder<ClavSession>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ClavSession> DECODER =
      new BinaryMessageDecoder<ClavSession>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ClavSession> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ClavSession> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ClavSession>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ClavSession to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ClavSession from a ByteBuffer. */
  public static ClavSession fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String sessionId;
  @Deprecated public int siteId;
  @Deprecated public long botFlag;
  @Deprecated public int validPageCount;
  @Deprecated public long duration;
  @Deprecated public int startPageId;
  @Deprecated public int exitPageId;
  @Deprecated public long startTimestamp;
  @Deprecated public long exitTimestamp;
  @Deprecated public int grCount;
  @Deprecated public int gr1Count;
  @Deprecated public int homepageCount;
  @Deprecated public int viCount;
  @Deprecated public int signinCount;
  @Deprecated public int myebayCount;
  @Deprecated public java.util.Map<java.lang.String,java.lang.String> others;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ClavSession() {}

  /**
   * All-args constructor.
   * @param sessionId The new value for sessionId
   * @param siteId The new value for siteId
   * @param botFlag The new value for botFlag
   * @param validPageCount The new value for validPageCount
   * @param duration The new value for duration
   * @param startPageId The new value for startPageId
   * @param exitPageId The new value for exitPageId
   * @param startTimestamp The new value for startTimestamp
   * @param exitTimestamp The new value for exitTimestamp
   * @param grCount The new value for grCount
   * @param gr1Count The new value for gr1Count
   * @param homepageCount The new value for homepageCount
   * @param viCount The new value for viCount
   * @param signinCount The new value for signinCount
   * @param myebayCount The new value for myebayCount
   * @param others The new value for others
   */
  public ClavSession(java.lang.String sessionId, java.lang.Integer siteId, java.lang.Long botFlag, java.lang.Integer validPageCount, java.lang.Long duration, java.lang.Integer startPageId, java.lang.Integer exitPageId, java.lang.Long startTimestamp, java.lang.Long exitTimestamp, java.lang.Integer grCount, java.lang.Integer gr1Count, java.lang.Integer homepageCount, java.lang.Integer viCount, java.lang.Integer signinCount, java.lang.Integer myebayCount, java.util.Map<java.lang.String,java.lang.String> others) {
    this.sessionId = sessionId;
    this.siteId = siteId;
    this.botFlag = botFlag;
    this.validPageCount = validPageCount;
    this.duration = duration;
    this.startPageId = startPageId;
    this.exitPageId = exitPageId;
    this.startTimestamp = startTimestamp;
    this.exitTimestamp = exitTimestamp;
    this.grCount = grCount;
    this.gr1Count = gr1Count;
    this.homepageCount = homepageCount;
    this.viCount = viCount;
    this.signinCount = signinCount;
    this.myebayCount = myebayCount;
    this.others = others;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sessionId;
    case 1: return siteId;
    case 2: return botFlag;
    case 3: return validPageCount;
    case 4: return duration;
    case 5: return startPageId;
    case 6: return exitPageId;
    case 7: return startTimestamp;
    case 8: return exitTimestamp;
    case 9: return grCount;
    case 10: return gr1Count;
    case 11: return homepageCount;
    case 12: return viCount;
    case 13: return signinCount;
    case 14: return myebayCount;
    case 15: return others;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sessionId = (java.lang.String)value$; break;
    case 1: siteId = (java.lang.Integer)value$; break;
    case 2: botFlag = (java.lang.Long)value$; break;
    case 3: validPageCount = (java.lang.Integer)value$; break;
    case 4: duration = (java.lang.Long)value$; break;
    case 5: startPageId = (java.lang.Integer)value$; break;
    case 6: exitPageId = (java.lang.Integer)value$; break;
    case 7: startTimestamp = (java.lang.Long)value$; break;
    case 8: exitTimestamp = (java.lang.Long)value$; break;
    case 9: grCount = (java.lang.Integer)value$; break;
    case 10: gr1Count = (java.lang.Integer)value$; break;
    case 11: homepageCount = (java.lang.Integer)value$; break;
    case 12: viCount = (java.lang.Integer)value$; break;
    case 13: signinCount = (java.lang.Integer)value$; break;
    case 14: myebayCount = (java.lang.Integer)value$; break;
    case 15: others = (java.util.Map<java.lang.String,java.lang.String>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sessionId' field.
   * @return The value of the 'sessionId' field.
   */
  public java.lang.String getSessionId() {
    return sessionId;
  }

  /**
   * Sets the value of the 'sessionId' field.
   * @param value the value to set.
   */
  public void setSessionId(java.lang.String value) {
    this.sessionId = value;
  }

  /**
   * Gets the value of the 'siteId' field.
   * @return The value of the 'siteId' field.
   */
  public java.lang.Integer getSiteId() {
    return siteId;
  }

  /**
   * Sets the value of the 'siteId' field.
   * @param value the value to set.
   */
  public void setSiteId(java.lang.Integer value) {
    this.siteId = value;
  }

  /**
   * Gets the value of the 'botFlag' field.
   * @return The value of the 'botFlag' field.
   */
  public java.lang.Long getBotFlag() {
    return botFlag;
  }

  /**
   * Sets the value of the 'botFlag' field.
   * @param value the value to set.
   */
  public void setBotFlag(java.lang.Long value) {
    this.botFlag = value;
  }

  /**
   * Gets the value of the 'validPageCount' field.
   * @return The value of the 'validPageCount' field.
   */
  public java.lang.Integer getValidPageCount() {
    return validPageCount;
  }

  /**
   * Sets the value of the 'validPageCount' field.
   * @param value the value to set.
   */
  public void setValidPageCount(java.lang.Integer value) {
    this.validPageCount = value;
  }

  /**
   * Gets the value of the 'duration' field.
   * @return The value of the 'duration' field.
   */
  public java.lang.Long getDuration() {
    return duration;
  }

  /**
   * Sets the value of the 'duration' field.
   * @param value the value to set.
   */
  public void setDuration(java.lang.Long value) {
    this.duration = value;
  }

  /**
   * Gets the value of the 'startPageId' field.
   * @return The value of the 'startPageId' field.
   */
  public java.lang.Integer getStartPageId() {
    return startPageId;
  }

  /**
   * Sets the value of the 'startPageId' field.
   * @param value the value to set.
   */
  public void setStartPageId(java.lang.Integer value) {
    this.startPageId = value;
  }

  /**
   * Gets the value of the 'exitPageId' field.
   * @return The value of the 'exitPageId' field.
   */
  public java.lang.Integer getExitPageId() {
    return exitPageId;
  }

  /**
   * Sets the value of the 'exitPageId' field.
   * @param value the value to set.
   */
  public void setExitPageId(java.lang.Integer value) {
    this.exitPageId = value;
  }

  /**
   * Gets the value of the 'startTimestamp' field.
   * @return The value of the 'startTimestamp' field.
   */
  public java.lang.Long getStartTimestamp() {
    return startTimestamp;
  }

  /**
   * Sets the value of the 'startTimestamp' field.
   * @param value the value to set.
   */
  public void setStartTimestamp(java.lang.Long value) {
    this.startTimestamp = value;
  }

  /**
   * Gets the value of the 'exitTimestamp' field.
   * @return The value of the 'exitTimestamp' field.
   */
  public java.lang.Long getExitTimestamp() {
    return exitTimestamp;
  }

  /**
   * Sets the value of the 'exitTimestamp' field.
   * @param value the value to set.
   */
  public void setExitTimestamp(java.lang.Long value) {
    this.exitTimestamp = value;
  }

  /**
   * Gets the value of the 'grCount' field.
   * @return The value of the 'grCount' field.
   */
  public java.lang.Integer getGrCount() {
    return grCount;
  }

  /**
   * Sets the value of the 'grCount' field.
   * @param value the value to set.
   */
  public void setGrCount(java.lang.Integer value) {
    this.grCount = value;
  }

  /**
   * Gets the value of the 'gr1Count' field.
   * @return The value of the 'gr1Count' field.
   */
  public java.lang.Integer getGr1Count() {
    return gr1Count;
  }

  /**
   * Sets the value of the 'gr1Count' field.
   * @param value the value to set.
   */
  public void setGr1Count(java.lang.Integer value) {
    this.gr1Count = value;
  }

  /**
   * Gets the value of the 'homepageCount' field.
   * @return The value of the 'homepageCount' field.
   */
  public java.lang.Integer getHomepageCount() {
    return homepageCount;
  }

  /**
   * Sets the value of the 'homepageCount' field.
   * @param value the value to set.
   */
  public void setHomepageCount(java.lang.Integer value) {
    this.homepageCount = value;
  }

  /**
   * Gets the value of the 'viCount' field.
   * @return The value of the 'viCount' field.
   */
  public java.lang.Integer getViCount() {
    return viCount;
  }

  /**
   * Sets the value of the 'viCount' field.
   * @param value the value to set.
   */
  public void setViCount(java.lang.Integer value) {
    this.viCount = value;
  }

  /**
   * Gets the value of the 'signinCount' field.
   * @return The value of the 'signinCount' field.
   */
  public java.lang.Integer getSigninCount() {
    return signinCount;
  }

  /**
   * Sets the value of the 'signinCount' field.
   * @param value the value to set.
   */
  public void setSigninCount(java.lang.Integer value) {
    this.signinCount = value;
  }

  /**
   * Gets the value of the 'myebayCount' field.
   * @return The value of the 'myebayCount' field.
   */
  public java.lang.Integer getMyebayCount() {
    return myebayCount;
  }

  /**
   * Sets the value of the 'myebayCount' field.
   * @param value the value to set.
   */
  public void setMyebayCount(java.lang.Integer value) {
    this.myebayCount = value;
  }

  /**
   * Gets the value of the 'others' field.
   * @return The value of the 'others' field.
   */
  public java.util.Map<java.lang.String,java.lang.String> getOthers() {
    return others;
  }

  /**
   * Sets the value of the 'others' field.
   * @param value the value to set.
   */
  public void setOthers(java.util.Map<java.lang.String,java.lang.String> value) {
    this.others = value;
  }

  /**
   * Creates a new ClavSession RecordBuilder.
   * @return A new ClavSession RecordBuilder
   */
  public static com.ebay.epic.soj.common.model.ClavSession.Builder newBuilder() {
    return new com.ebay.epic.soj.common.model.ClavSession.Builder();
  }

  /**
   * Creates a new ClavSession RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ClavSession RecordBuilder
   */
  public static com.ebay.epic.soj.common.model.ClavSession.Builder newBuilder(com.ebay.epic.soj.common.model.ClavSession.Builder other) {
    return new com.ebay.epic.soj.common.model.ClavSession.Builder(other);
  }

  /**
   * Creates a new ClavSession RecordBuilder by copying an existing ClavSession instance.
   * @param other The existing instance to copy.
   * @return A new ClavSession RecordBuilder
   */
  public static com.ebay.epic.soj.common.model.ClavSession.Builder newBuilder(com.ebay.epic.soj.common.model.ClavSession other) {
    return new com.ebay.epic.soj.common.model.ClavSession.Builder(other);
  }

  /**
   * RecordBuilder for ClavSession instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ClavSession>
    implements org.apache.avro.data.RecordBuilder<ClavSession> {

    private java.lang.String sessionId;
    private int siteId;
    private long botFlag;
    private int validPageCount;
    private long duration;
    private int startPageId;
    private int exitPageId;
    private long startTimestamp;
    private long exitTimestamp;
    private int grCount;
    private int gr1Count;
    private int homepageCount;
    private int viCount;
    private int signinCount;
    private int myebayCount;
    private java.util.Map<java.lang.String,java.lang.String> others;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ebay.epic.soj.common.model.ClavSession.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sessionId)) {
        this.sessionId = data().deepCopy(fields()[0].schema(), other.sessionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.siteId)) {
        this.siteId = data().deepCopy(fields()[1].schema(), other.siteId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.botFlag)) {
        this.botFlag = data().deepCopy(fields()[2].schema(), other.botFlag);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.validPageCount)) {
        this.validPageCount = data().deepCopy(fields()[3].schema(), other.validPageCount);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.duration)) {
        this.duration = data().deepCopy(fields()[4].schema(), other.duration);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.startPageId)) {
        this.startPageId = data().deepCopy(fields()[5].schema(), other.startPageId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.exitPageId)) {
        this.exitPageId = data().deepCopy(fields()[6].schema(), other.exitPageId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.startTimestamp)) {
        this.startTimestamp = data().deepCopy(fields()[7].schema(), other.startTimestamp);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.exitTimestamp)) {
        this.exitTimestamp = data().deepCopy(fields()[8].schema(), other.exitTimestamp);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.grCount)) {
        this.grCount = data().deepCopy(fields()[9].schema(), other.grCount);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.gr1Count)) {
        this.gr1Count = data().deepCopy(fields()[10].schema(), other.gr1Count);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.homepageCount)) {
        this.homepageCount = data().deepCopy(fields()[11].schema(), other.homepageCount);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.viCount)) {
        this.viCount = data().deepCopy(fields()[12].schema(), other.viCount);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.signinCount)) {
        this.signinCount = data().deepCopy(fields()[13].schema(), other.signinCount);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.myebayCount)) {
        this.myebayCount = data().deepCopy(fields()[14].schema(), other.myebayCount);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.others)) {
        this.others = data().deepCopy(fields()[15].schema(), other.others);
        fieldSetFlags()[15] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ClavSession instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ebay.epic.soj.common.model.ClavSession other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.sessionId)) {
        this.sessionId = data().deepCopy(fields()[0].schema(), other.sessionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.siteId)) {
        this.siteId = data().deepCopy(fields()[1].schema(), other.siteId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.botFlag)) {
        this.botFlag = data().deepCopy(fields()[2].schema(), other.botFlag);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.validPageCount)) {
        this.validPageCount = data().deepCopy(fields()[3].schema(), other.validPageCount);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.duration)) {
        this.duration = data().deepCopy(fields()[4].schema(), other.duration);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.startPageId)) {
        this.startPageId = data().deepCopy(fields()[5].schema(), other.startPageId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.exitPageId)) {
        this.exitPageId = data().deepCopy(fields()[6].schema(), other.exitPageId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.startTimestamp)) {
        this.startTimestamp = data().deepCopy(fields()[7].schema(), other.startTimestamp);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.exitTimestamp)) {
        this.exitTimestamp = data().deepCopy(fields()[8].schema(), other.exitTimestamp);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.grCount)) {
        this.grCount = data().deepCopy(fields()[9].schema(), other.grCount);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.gr1Count)) {
        this.gr1Count = data().deepCopy(fields()[10].schema(), other.gr1Count);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.homepageCount)) {
        this.homepageCount = data().deepCopy(fields()[11].schema(), other.homepageCount);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.viCount)) {
        this.viCount = data().deepCopy(fields()[12].schema(), other.viCount);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.signinCount)) {
        this.signinCount = data().deepCopy(fields()[13].schema(), other.signinCount);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.myebayCount)) {
        this.myebayCount = data().deepCopy(fields()[14].schema(), other.myebayCount);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.others)) {
        this.others = data().deepCopy(fields()[15].schema(), other.others);
        fieldSetFlags()[15] = true;
      }
    }

    /**
      * Gets the value of the 'sessionId' field.
      * @return The value.
      */
    public java.lang.String getSessionId() {
      return sessionId;
    }

    /**
      * Sets the value of the 'sessionId' field.
      * @param value The value of 'sessionId'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setSessionId(java.lang.String value) {
      validate(fields()[0], value);
      this.sessionId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sessionId' field has been set.
      * @return True if the 'sessionId' field has been set, false otherwise.
      */
    public boolean hasSessionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sessionId' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearSessionId() {
      sessionId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'siteId' field.
      * @return The value.
      */
    public java.lang.Integer getSiteId() {
      return siteId;
    }

    /**
      * Sets the value of the 'siteId' field.
      * @param value The value of 'siteId'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setSiteId(int value) {
      validate(fields()[1], value);
      this.siteId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'siteId' field has been set.
      * @return True if the 'siteId' field has been set, false otherwise.
      */
    public boolean hasSiteId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'siteId' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearSiteId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'botFlag' field.
      * @return The value.
      */
    public java.lang.Long getBotFlag() {
      return botFlag;
    }

    /**
      * Sets the value of the 'botFlag' field.
      * @param value The value of 'botFlag'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setBotFlag(long value) {
      validate(fields()[2], value);
      this.botFlag = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'botFlag' field has been set.
      * @return True if the 'botFlag' field has been set, false otherwise.
      */
    public boolean hasBotFlag() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'botFlag' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearBotFlag() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'validPageCount' field.
      * @return The value.
      */
    public java.lang.Integer getValidPageCount() {
      return validPageCount;
    }

    /**
      * Sets the value of the 'validPageCount' field.
      * @param value The value of 'validPageCount'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setValidPageCount(int value) {
      validate(fields()[3], value);
      this.validPageCount = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'validPageCount' field has been set.
      * @return True if the 'validPageCount' field has been set, false otherwise.
      */
    public boolean hasValidPageCount() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'validPageCount' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearValidPageCount() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'duration' field.
      * @return The value.
      */
    public java.lang.Long getDuration() {
      return duration;
    }

    /**
      * Sets the value of the 'duration' field.
      * @param value The value of 'duration'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setDuration(long value) {
      validate(fields()[4], value);
      this.duration = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'duration' field has been set.
      * @return True if the 'duration' field has been set, false otherwise.
      */
    public boolean hasDuration() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'duration' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearDuration() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'startPageId' field.
      * @return The value.
      */
    public java.lang.Integer getStartPageId() {
      return startPageId;
    }

    /**
      * Sets the value of the 'startPageId' field.
      * @param value The value of 'startPageId'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setStartPageId(int value) {
      validate(fields()[5], value);
      this.startPageId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'startPageId' field has been set.
      * @return True if the 'startPageId' field has been set, false otherwise.
      */
    public boolean hasStartPageId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'startPageId' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearStartPageId() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'exitPageId' field.
      * @return The value.
      */
    public java.lang.Integer getExitPageId() {
      return exitPageId;
    }

    /**
      * Sets the value of the 'exitPageId' field.
      * @param value The value of 'exitPageId'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setExitPageId(int value) {
      validate(fields()[6], value);
      this.exitPageId = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'exitPageId' field has been set.
      * @return True if the 'exitPageId' field has been set, false otherwise.
      */
    public boolean hasExitPageId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'exitPageId' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearExitPageId() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'startTimestamp' field.
      * @return The value.
      */
    public java.lang.Long getStartTimestamp() {
      return startTimestamp;
    }

    /**
      * Sets the value of the 'startTimestamp' field.
      * @param value The value of 'startTimestamp'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setStartTimestamp(long value) {
      validate(fields()[7], value);
      this.startTimestamp = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'startTimestamp' field has been set.
      * @return True if the 'startTimestamp' field has been set, false otherwise.
      */
    public boolean hasStartTimestamp() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'startTimestamp' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearStartTimestamp() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'exitTimestamp' field.
      * @return The value.
      */
    public java.lang.Long getExitTimestamp() {
      return exitTimestamp;
    }

    /**
      * Sets the value of the 'exitTimestamp' field.
      * @param value The value of 'exitTimestamp'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setExitTimestamp(long value) {
      validate(fields()[8], value);
      this.exitTimestamp = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'exitTimestamp' field has been set.
      * @return True if the 'exitTimestamp' field has been set, false otherwise.
      */
    public boolean hasExitTimestamp() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'exitTimestamp' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearExitTimestamp() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'grCount' field.
      * @return The value.
      */
    public java.lang.Integer getGrCount() {
      return grCount;
    }

    /**
      * Sets the value of the 'grCount' field.
      * @param value The value of 'grCount'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setGrCount(int value) {
      validate(fields()[9], value);
      this.grCount = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'grCount' field has been set.
      * @return True if the 'grCount' field has been set, false otherwise.
      */
    public boolean hasGrCount() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'grCount' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearGrCount() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'gr1Count' field.
      * @return The value.
      */
    public java.lang.Integer getGr1Count() {
      return gr1Count;
    }

    /**
      * Sets the value of the 'gr1Count' field.
      * @param value The value of 'gr1Count'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setGr1Count(int value) {
      validate(fields()[10], value);
      this.gr1Count = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'gr1Count' field has been set.
      * @return True if the 'gr1Count' field has been set, false otherwise.
      */
    public boolean hasGr1Count() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'gr1Count' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearGr1Count() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'homepageCount' field.
      * @return The value.
      */
    public java.lang.Integer getHomepageCount() {
      return homepageCount;
    }

    /**
      * Sets the value of the 'homepageCount' field.
      * @param value The value of 'homepageCount'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setHomepageCount(int value) {
      validate(fields()[11], value);
      this.homepageCount = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'homepageCount' field has been set.
      * @return True if the 'homepageCount' field has been set, false otherwise.
      */
    public boolean hasHomepageCount() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'homepageCount' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearHomepageCount() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'viCount' field.
      * @return The value.
      */
    public java.lang.Integer getViCount() {
      return viCount;
    }

    /**
      * Sets the value of the 'viCount' field.
      * @param value The value of 'viCount'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setViCount(int value) {
      validate(fields()[12], value);
      this.viCount = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'viCount' field has been set.
      * @return True if the 'viCount' field has been set, false otherwise.
      */
    public boolean hasViCount() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'viCount' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearViCount() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'signinCount' field.
      * @return The value.
      */
    public java.lang.Integer getSigninCount() {
      return signinCount;
    }

    /**
      * Sets the value of the 'signinCount' field.
      * @param value The value of 'signinCount'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setSigninCount(int value) {
      validate(fields()[13], value);
      this.signinCount = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'signinCount' field has been set.
      * @return True if the 'signinCount' field has been set, false otherwise.
      */
    public boolean hasSigninCount() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'signinCount' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearSigninCount() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'myebayCount' field.
      * @return The value.
      */
    public java.lang.Integer getMyebayCount() {
      return myebayCount;
    }

    /**
      * Sets the value of the 'myebayCount' field.
      * @param value The value of 'myebayCount'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setMyebayCount(int value) {
      validate(fields()[14], value);
      this.myebayCount = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'myebayCount' field has been set.
      * @return True if the 'myebayCount' field has been set, false otherwise.
      */
    public boolean hasMyebayCount() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'myebayCount' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearMyebayCount() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'others' field.
      * @return The value.
      */
    public java.util.Map<java.lang.String,java.lang.String> getOthers() {
      return others;
    }

    /**
      * Sets the value of the 'others' field.
      * @param value The value of 'others'.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder setOthers(java.util.Map<java.lang.String,java.lang.String> value) {
      validate(fields()[15], value);
      this.others = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'others' field has been set.
      * @return True if the 'others' field has been set, false otherwise.
      */
    public boolean hasOthers() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'others' field.
      * @return This builder.
      */
    public com.ebay.epic.soj.common.model.ClavSession.Builder clearOthers() {
      others = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ClavSession build() {
      try {
        ClavSession record = new ClavSession();
        record.sessionId = fieldSetFlags()[0] ? this.sessionId : (java.lang.String) defaultValue(fields()[0]);
        record.siteId = fieldSetFlags()[1] ? this.siteId : (java.lang.Integer) defaultValue(fields()[1]);
        record.botFlag = fieldSetFlags()[2] ? this.botFlag : (java.lang.Long) defaultValue(fields()[2]);
        record.validPageCount = fieldSetFlags()[3] ? this.validPageCount : (java.lang.Integer) defaultValue(fields()[3]);
        record.duration = fieldSetFlags()[4] ? this.duration : (java.lang.Long) defaultValue(fields()[4]);
        record.startPageId = fieldSetFlags()[5] ? this.startPageId : (java.lang.Integer) defaultValue(fields()[5]);
        record.exitPageId = fieldSetFlags()[6] ? this.exitPageId : (java.lang.Integer) defaultValue(fields()[6]);
        record.startTimestamp = fieldSetFlags()[7] ? this.startTimestamp : (java.lang.Long) defaultValue(fields()[7]);
        record.exitTimestamp = fieldSetFlags()[8] ? this.exitTimestamp : (java.lang.Long) defaultValue(fields()[8]);
        record.grCount = fieldSetFlags()[9] ? this.grCount : (java.lang.Integer) defaultValue(fields()[9]);
        record.gr1Count = fieldSetFlags()[10] ? this.gr1Count : (java.lang.Integer) defaultValue(fields()[10]);
        record.homepageCount = fieldSetFlags()[11] ? this.homepageCount : (java.lang.Integer) defaultValue(fields()[11]);
        record.viCount = fieldSetFlags()[12] ? this.viCount : (java.lang.Integer) defaultValue(fields()[12]);
        record.signinCount = fieldSetFlags()[13] ? this.signinCount : (java.lang.Integer) defaultValue(fields()[13]);
        record.myebayCount = fieldSetFlags()[14] ? this.myebayCount : (java.lang.Integer) defaultValue(fields()[14]);
        record.others = fieldSetFlags()[15] ? this.others : (java.util.Map<java.lang.String,java.lang.String>) defaultValue(fields()[15]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ClavSession>
    WRITER$ = (org.apache.avro.io.DatumWriter<ClavSession>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ClavSession>
    READER$ = (org.apache.avro.io.DatumReader<ClavSession>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
