flink:
  app:
    name: Unified Sessionization Test
    parallelism:
      default: 50
      source:
        autotrack:
          web:
            nonbot: 50
          native:
            nonbot: 10
        ubi:
          ubi:
            nonbot: 400
            bot: 400
        utp:
          utp:
            nonbot: 80
      pre-filter:
        autotrack:
          web:
            nonbot: 50
          native:
            nonbot: 10
        ubi:
          ubi:
            nonbot: 400
            bot: 400
        utp:
          utp:
            nonbot: 80
      normalizer:
        autotrack:
          web:
            nonbot: 50
          native:
            nonbot: 10
        ubi:
          ubi:
            nonbot: 400
            bot: 400
        utp:
          utp:
            nonbot: 80
      session: 1260
      split:
        default: 1260
        late: 1260
        session: 1260
      sink-kafka:
        autotrack: 1260
        ubi: 1260
        utp: 1260
        session: 1260
        late: 1260
      max:
        default: 2400
        session: 5040
        sink: 5040
    checkpoint:
      data-dir: /opt/tracking-behavior/checkpoint
      interval-ms: 300000
      timeout-ms: 900000
      min-pause-between-ms: 120000
      max-concurrent: 1
      tolerate-failure-number: 3
    source:
      from-timestamp:
        autotrack: 0
        ubi: 0
        utp: 0
      out-of-orderless-in-min:
        autotrack: 3
        ubi: 3
        utp: 3
      idle-source-timeout-in-min:
        autotrack: 10
        ubi: 10
        utp: 10
    sink:
      message-key: guid
      sampling-key: guid
      sampling-pct: 10
      allow-drop: true
      dc: rno
      kafka:
        topic:
          autotrack:
            web:
              nonbot: behavior.unified.surface.event.sessionized-rno
            native:
              nonbot: behavior.unified.surface.native.event.sessionized-rno
          ubi:
            ubi:
              bot: behavior.unified.sojourner.bot.sojevent-rno
              nonbot: behavior.unified.sojourner.nonbot.sojevent-rno
          utp:
            utp:
              nonbot: behavior.total.new.utpevent
          late:
              web:
                nonbot: behavior.unified.surface.late.event.web-rno
              native:
                nonbot: behavior.unified.surface.late.event.native-rno
              ubi:
                bot: behavior.unified.sojourner.bot.late.sojevent-rno
                nonbot: behavior.unified.sojourner.nonbot.late.sojevent-rno
          session:
            session:
              nonbot: behavior.unified.sojourner.nonbot.unisession-test-rno
        subject:
          autotrack: SessionizedEvent
          ubi: behavior.sojourner.sojevent.schema
          utp: UnifiedTrackingRheosEvent
          session: UniSessionTest
    metric:
      window-size: 70000
    slot-sharing-group:
      source:
        autotrack: autotrack-source
        ubi: sojourner-source
        utp: marketing-tracking-source
      pre-filter:
        autotrack: autotrack-source
        ubi: sojourner-source
        utp: marketing-tracking-source
      normalizer:
        autotrack: autotrack-source
        ubi: sojourner-source
        utp: marketing-tracking-source
      session-window: session-operator
      split: session-operator
      sink:
        default: session-operator
#        autotrack: autotrack-sink-to-kafka
#        ubi: sojourner-sink-to-kafka
#        utp: marketing-tracking-sink-to-kafka
#        late: late-event-sink-to-kafka
#        session: unisession-sink-to-kafka
    operator-name:
      source:
        autotrack: AutoTrack Source
        ubi: Sojourner Source
        utp: Marketing Tracking Source
      pre-filter:
        autotrack: AutoTrack PreFilter Operator
        ubi: Sojourner PreFilter Operator
        utp: Marketing PreFilter Operator
      normalizer:
        autotrack: AutoTrack Normalizer Operator
        ubi: Sojourner Normalizer Operator
        utp: Marketing Normalizer Operator
      session-window: Session Operator
      split:
        default: Main Split Operator
        late: Late Split Operator
        session: Session Split Operator
      sink:
        autotrack: AutoTracking Sink to Kafka
        ubi: Sojourner Sink to Kafka
        utp: Marketing Tracking Sink To Kafka
        session: UniSession Sink to Kafka
        late: Late Event Sink to Kafka
    uid:
      source:
        autotrack: autotrack-source
        ubi: sojourner-source
        utp: marketing-tracking-source
      pre-filter:
        autotrack: autotrack-prefilter-operator
        ubi: sojourner-prefilter-operator
        utp: marketing-tracking-prefilter-operator
      normalizer:
        autotrack: autotrack-normalizer-0perator
        ubi: sojourner-normalizer-0perator
        utp: marketing-tracking-normalizer-0perator
      session-window: session-operator
      split:
        default: main-split-operator
        late: late-split-operator
        session: session-split-operator
      sink:
        autotrack: autotracking-sink-to-kafka
        ubi: sojourner-sink-to-kafka
        utp: marketing-tracking-sink-to-kafka
        session: unisession-sink-to-kafka
        late: late-event-sink-to-kafka
kafka:
  consumer:
      group-id: unified-sessionization-test
      topic:
        autotrack:
          web:
            nonbot:
              - behavior.autotracking.native.event.sessionized
          native:
            nonbot:
              - behavior.autotracking.event.sessionized
        ubi:
          ubi:
            nonbot:
              - behavior.totalv3.sojevent-nonbot-rno
              - behavior.totalv3.sojevent-nonbot-lvs
            bot:
              - behavior.totalv3.sojevent-bot-rno
              - behavior.totalv3.sojevent-bot-lvs
        utp:
          utp:
            nonbot:
              - marketing.tracking.events.total

      bootstrap-servers:
        rno:
          autotrack:
            - rhs-bkuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092
            - rhs-bkuvkiaa-kfk-rno-2.rheos-slstreaming-prod.svc.26.tess.io:9092
            - rhs-bkuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092
            - rhs-bkuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.26.tess.io:9092
            - rhs-bkuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.26.tess.io:9092
          ubi:
            - rhs-lpdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
            - rhs-lpdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
            - rhs-lpdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
            - rhs-lpdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
            - rhs-lpdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
        lvs:
          autotrack:
            - rhs-lpuvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.27.tess.io:9092
            - rhs-lpuvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.27.tess.io:9092
            - rhs-lpuvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.27.tess.io:9092
            - rhs-lpuvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.27.tess.io:9092
            - rhs-lpuvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.27.tess.io:9092
          ubi:
            - rhs-opdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
            - rhs-opdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
            - rhs-opdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
            - rhs-opdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
            - rhs-opdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
          utp:
            - rhs-hcrvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.27.tess.io:9092
            - rhs-hcrvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.27.tess.io:9092
            - rhs-hcrvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.27.tess.io:9092
            - rhs-hcrvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.27.tess.io:9092
            - rhs-hcrvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.27.tess.io:9092
        slc:
          autotrack:
            - rhs-gpuvkiaa-kfk-slc-1.rheos-streaming-prod.svc.40.tess.io:9092
            - rhs-gpuvkiaa-kfk-slc-2.rheos-streaming-prod.svc.40.tess.io:9092
            - rhs-gpuvkiaa-kfk-slc-3.rheos-streaming-prod.svc.40.tess.io:9092
            - rhs-gpuvkiaa-kfk-slc-4.rheos-streaming-prod.svc.40.tess.io:9092
            - rhs-gpuvkiaa-kfk-slc-5.rheos-streaming-prod.svc.40.tess.io:9092
          utp:
            - rhs-ncrvkiaa-kfk-slc-1.rheos-streaming-prod.svc.40.tess.io:9092
            - rhs-ncrvkiaa-kfk-slc-2.rheos-streaming-prod.svc.40.tess.io:9092
            - rhs-ncrvkiaa-kfk-slc-3.rheos-streaming-prod.svc.40.tess.io:9092
            - rhs-ncrvkiaa-kfk-slc-4.rheos-streaming-prod.svc.40.tess.io:9092
            - rhs-ncrvkiaa-kfk-slc-5.rheos-streaming-prod.svc.40.tess.io:9092
      max-poll-records:
        default: 6000
      # 16MB, default value is 50MB
      fetch-max-bytes:
        default: 16777216
      # 128KB, default value is 64KB
      receive-buffer:
        default: 131072
      fetch-max-wait-ms:
        default: 100
      # 4MB, default value is 1MB
      max-partitions-fetch-bytes:
        default: 4194304
      auto-offset-reset:
        default: latest
      partition-discovery-interval-ms:
        default: 60000
  # TODO after finalize the stream name and DC
  producer:
    stream: behavior.
    producerId: unified-sessionization-prod
    bootstrap-servers:
      rno:
        autotrack:
          web:
            nonbot:
              - rhs-xfcwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-xfcwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-xfcwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-xfcwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-xfcwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
          native:
            nonbot:
              - rhs-xfcwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-xfcwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-xfcwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-xfcwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-xfcwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
        ubi:
          ubi:
            nonbot:
              - rhs-ddcwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-ddcwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-ddcwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-ddcwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-ddcwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
            bot:
              - rhs-necwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-necwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-necwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-necwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-necwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
        utp:
          utp:
            nonbot:
              - rhs-pbuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092
              - rhs-pbuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092
              - rhs-pbuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092
              - rhs-pbuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.26.tess.io:9092
              - rhs-pbuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.26.tess.io:9092
        late:
          web:
            nonbot:
              - rhs-xfcwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-xfcwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-xfcwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-xfcwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-xfcwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
          native:
            nonbot:
              - rhs-xfcwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-xfcwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-xfcwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-xfcwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-xfcwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
          ubi:
            nonbot:
              - rhs-ddcwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-ddcwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-ddcwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-ddcwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-ddcwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
            bot:
              - rhs-necwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-necwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-necwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-necwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-necwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
        session:
          session:
            bot:
              - rhs-ddcwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-ddcwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-ddcwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-ddcwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-ddcwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
            nonbot:
              - rhs-ddcwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-ddcwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-ddcwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-ddcwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-ddcwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
    batch-size:
      default: 524288
    acks:
      default: 1
    linger-ms:
      default: 50
    # 30s
    request-timeout-ms:
      default: 30000
    retries:
      default: 30
    buffer-memory:
      default: 268435456
    compression-type:
      default: lz4
    # 2min
    delivery-timeout-ms:
      default: 120000
    # 1000000 byte
    max-request-size:
      default: 1000000

rheos:
  registry-url: https://rheos-services.stratus.ebay.com
  client:
    id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
    iaf:
      secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
      env: production

rest-client:
  base-url: https://sojsvc.vip.ebay.com
  username: soj-flink-app
  config:
    pull-interval: 30000
    env: prod
