flink:
  app:
    name: Unified Sessionization Preprod
    source:
      from-timestamp:
        autotrack: latest
        ubi: latest
        utp: latest
        roi: latest
    sink:
      kafka:
        topic:
          autotrack:
            web:
              nonbot: behavior.total.new.surfaceevent
            native:
              nonbot: behavior.total.new.surfaceevent.native
          ubi:
            ubi:
              bot: behavior.total.new.sojevent-poc
              nonbot: behavior.total.new.sojevent-poc
          utp:
            utp:
              nonbot: behavior.total.new.utpevent
          roi:
            roi:
              nonbot: behavior.total.new.globalevents.roi
          session:
            session:
              nonbot: behavior.total.new.unisession
            sessionlkp:
              nonbot: behavior.total.new.unisessionlkp
          late:
            web:
              nonbot: behavior.total.new.surfaceevent
            native:
              nonbot: behavior.total.new.surfaceevent.native
            ubi:
              bot: behavior.total.new.sojevent-late-bot-poc
              nonbot: behavior.total.new.sojevent-late-nonbot-poc
            roi:
              nonbot: behavior.total.new.late.globalevents.roi
        subject:
          session: unifiedsessionschemanew
      message-key: guid
      sampling-key: guid
      sampling-pct: 10
      allow-drop: true
      dc: rno
    uid:
      source:
        autotrack: autotrack-source-preprod
        ubi: sojourner-source-preprod
        utp: marketing-tracking-source-preprod
        roi: roi-source-preprod
      sink:
        autotrack: autotracking-sink-to-kafka-preprod
        ubi: sojourner-sink-to-kafka-preprod
        utp: marketing-tracking-sink-to-kafka-preprod
        session: unisession-sink-to-kafka-preprod
        late: late-event-sink-to-kafka-preprod
        roi: roi-sink-to-kafka-preprod
kafka:
  consumer:
    group-id: unified-sessionization-preprod
    topic:
      ubi:
        ubi:
          nonbot:
            - behavior.totalv3.sojevent-nonbot-rno
            - behavior.totalv3.sojevent-nonbot-lvs
          bot:
            - behavior.totalv3.sojevent-bot-rno
            - behavior.totalv3.sojevent-bot-lvs
    bootstrap-servers:
      rno:
        ubi:
          - rhs-lpdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
          - rhs-lpdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
          - rhs-lpdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
          - rhs-lpdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
          - rhs-lpdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
      lvs:
        ubi:
          - rhs-opdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
          - rhs-opdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
          - rhs-opdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
          - rhs-opdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
          - rhs-opdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
  producer:
    stream: behavior.
    producerId: unified-sessionization-preprod
    bootstrap-servers:
      rno:
        autotrack:
          web:
            nonbot:
              - rhs-pbuvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
          native:
            nonbot:
              - rhs-pbuvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
        ubi:
          ubi:
            nonbot:
              - rhs-pbuvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
            bot:
              - rhs-pbuvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
        utp:
          utp:
            nonbot:
              - rhs-pbuvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
        roi:
          roi:
            nonbot:
              - rhs-pbuvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
        session:
          session:
            bot:
              - rhs-pbuvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
            nonbot:
              - rhs-pbuvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
          sessionlkp:
            bot:
              - rhs-pbuvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
            nonbot:
              - rhs-pbuvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092

        late:
          roi:
            nonbot:
              - rhs-pbuvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
          native:
            nonbot:
              - rhs-pbuvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
          web:
            nonbot:
              - rhs-pbuvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
          ubi:
            bot:
              - rhs-pbuvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
            nonbot:
              - rhs-pbuvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
              - rhs-pbuvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092