flink:
  app:
    name: Unified Sessionization Prod
    parallelism:
      default: 50
      source:
        autotrack: 60
        ubi: 200
        utp: 80
      pre-filter: 400
      normalizer: 600
      session: 600
      post-filter:
        autotrack: 200
        ubi: 200
        utp: 100
      sink-kafka:
        autotrack: 200
        ubi: 200
        utp: 100
        session: 50
      max: 2000
    checkpoint:
      data-dir: /opt/tracking-behavior/checkpoint
      interval-ms: 300000
      timeout-ms: 900000
      min-pause-between-ms: 120000
      max-concurrent: 1
      tolerate-failure-number: 3
    source:
      from-timestamp:
        autotrack: 0
        ubi: 0
        utp: 0
      out-of-orderless-in-min:
        autotrack: 3
        ubi: 3
        utp: 3
      idle-source-timeout-in-min:
        autotrack: 10
        ubi: 10
        utp: 10
    sink:
      message-key: guid
      sampling-key: guid
      sampling-pct: 10
      allow-drop: true
      dc: rno
      kafka:
        topic:
          autotrack: behavior.total.new.surfaceevent
          ubi: behavior.total.new.sojevent-poc
          utp: behavior.total.new.utpevent
          session: behavior.total.new.unisession
        subject:
          autotrack: SessionizedEvent
          ubi: behavior.sojourner.sojevent.schema
          utp: UnifiedTrackingRheosEvent
          session: unisessionschema
    slot-sharing-group:
      source:
        autotrack: autotrack-source
        ubi: sojourner-source
        utp: marketing-tracking-source
      pre-filter: prefilter-operator
      normalizer: prefilter-operator
      session-window: session-operator
      post-filter: postfilter-operator
      sink:
        autotrack: autotrack-sink-to-kafka
        ubi: sojourner-sink-to-kafka
        utp: marketing-tracking-sink-to-kafka
        session: unisession-sink-to-kafka
    operator-name:
      source:
        autotrack: AutoTrack Source
        ubi: Sojourner Source
        utp: Marketing Tracking Source
      pre-filter: PreFilter Operator
      normalizer: Normalizer Operator
      session-window: Session Operator
      post-filter:
        autotrack: AutoTrack PostFilter Operator
        ubi: UBI PostFilter Operator
        utp: UTP PostFilter Operator
      sink:
        autotrack: AutoTracking Sink to Kafka
        ubi: Sojourner Sink to Kafka
        utp: Marketing Tracking Sink To Kafka
        session: UniSession Sink to Kafka
    uid:
      source:
        autotrack: autotrack-source
        ubi: sojourner-source
        utp: marketing-tracking-source
      pre-filter: prefilter-operator
      normalizer: normalizer-0perator
      session-window: session-operator
      post-filter:
        autotrack: autotrack-postFilter-operator
        ubi: ubi-postFilter-operator
        utp: utp-postFilter-operator
      sink:
        autotrack: autotracking-sink-to-kafka
        ubi: sojourner-sink-to-kafka
        utp: marketing-tracking-sink-to-kafka
        session: unisession-sink-to-kafka
kafka:
  consumer:
      group-id: unified-sessionization-prod
      topic:
        autotrack:
          - behavior.autotracking.native.event.sessionized
          - behavior.autotracking.event.sessionized
        ubi:
          - behavior.totalv2.sojevent-nonbot-rno
          - behavior.totalv2.sojevent-nonbot-lvs
          - behavior.totalv2.sojevent-bot-rno
          - behavior.totalv2.sojevent-bot-lvs
        utp:
          - marketing.tracking.events.total
      bootstrap-servers:
        rno:
          autotrack:
            - rhs-bkuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092
            - rhs-bkuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092
            - rhs-bkuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092
            - rhs-bkuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.26.tess.io:9092
            - rhs-bkuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.26.tess.io:9092
          ubi:
            - rhs-fxuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.37.tess.io:9092
            - rhs-fxuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.37.tess.io:9092
            - rhs-fxuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.37.tess.io:9092
            - rhs-fxuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.37.tess.io:9092
            - rhs-fxuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.37.tess.io:9092
        lvs:
          autotrack:
            - rhs-lpuvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.27.tess.io:9092
            - rhs-lpuvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.27.tess.io:9092
            - rhs-lpuvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.27.tess.io:9092
            - rhs-lpuvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.27.tess.io:9092
            - rhs-lpuvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.27.tess.io:9092
          ubi:
            - rhs-ravvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
            - rhs-ravvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
            - rhs-ravvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
            - rhs-ravvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
            - rhs-ravvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092
          utp:
            - rhs-hcrvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.27.tess.io:9092
            - rhs-hcrvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.27.tess.io:9092
            - rhs-hcrvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.27.tess.io:9092
            - rhs-hcrvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.27.tess.io:9092
            - rhs-hcrvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.27.tess.io:9092
        slc:
          autotrack:
            - rhs-gpuvkiaa-kfk-slc-1.rheos-streaming-prod.svc.40.tess.io:9092
            - rhs-gpuvkiaa-kfk-slc-2.rheos-streaming-prod.svc.40.tess.io:9092
            - rhs-gpuvkiaa-kfk-slc-3.rheos-streaming-prod.svc.40.tess.io:9092
            - rhs-gpuvkiaa-kfk-slc-4.rheos-streaming-prod.svc.40.tess.io:9092
            - rhs-gpuvkiaa-kfk-slc-5.rheos-streaming-prod.svc.40.tess.io:9092
          utp:
            - rhs-ncrvkiaa-kfk-slc-1.rheos-streaming-prod.svc.40.tess.io:9092
            - rhs-ncrvkiaa-kfk-slc-2.rheos-streaming-prod.svc.40.tess.io:9092
            - rhs-ncrvkiaa-kfk-slc-3.rheos-streaming-prod.svc.40.tess.io:9092
            - rhs-ncrvkiaa-kfk-slc-4.rheos-streaming-prod.svc.40.tess.io:9092
            - rhs-ncrvkiaa-kfk-slc-5.rheos-streaming-prod.svc.40.tess.io:9092
      max-poll-records:
        default: 3000
      # 16MB, default value is 50MB
      fetch-max-bytes:
        default: 16777216
      # 128KB, default value is 64KB
      receive-buffer:
        default: 131072
      fetch-max-wait-ms:
        default: 100
      # 4MB, default value is 1MB
      max-partitions-fetch-bytes:
        default: 4194304
      auto-offset-reset:
        default: latest
      partition-discovery-interval-ms:
        default: 60000
  # TODO after finalize the stream name and DC
  producer:
    stream: behavior.
    producerId: unified-sessionization-prod
    bootstrap-servers:
      rno:
        autotrack:
          - rhs-pbuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092
          - rhs-pbuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092
          - rhs-pbuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092
          - rhs-pbuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.26.tess.io:9092
          - rhs-pbuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.26.tess.io:9092
        ubi:
          - rhs-pbuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092
          - rhs-pbuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092
          - rhs-pbuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092
          - rhs-pbuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.26.tess.io:9092
          - rhs-pbuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.26.tess.io:9092
        utp:
          - rhs-pbuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092
          - rhs-pbuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092
          - rhs-pbuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092
          - rhs-pbuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.26.tess.io:9092
          - rhs-pbuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.26.tess.io:9092
        session:
          - rhs-pbuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092
          - rhs-pbuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092
          - rhs-pbuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092
          - rhs-pbuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.26.tess.io:9092
          - rhs-pbuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.26.tess.io:9092
    batch-size:
      default: 524288
    acks:
      default: 1
    linger-ms:
      default: 50
    # 30s
    request-timeout-ms:
      default: 30000
    retries:
      default: 30
    buffer-memory:
      default: 268435456
    compression-type:
      default: lz4
    # 2min
    delivery-timeout-ms:
      default: 120000
    # 1000000 byte
    max-request-size:
      default: 1000000

rheos:
  registry-url: https://rheos-services.stratus.ebay.com
  client:
    id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
    iaf:
      secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
      env: production

rest-client:
  base-url: https://sojsvc.vip.ebay.com
  username: soj-flink-app
  config:
    pull-interval: 30000
    env: prod
