/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ebay.epic.common.model;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum FormFactor {
  phone, tablet, watch, desktop  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FormFactor\",\"namespace\":\"com.ebay.epic.common.model\",\"symbols\":[\"phone\",\"tablet\",\"watch\",\"desktop\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
