/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ebay.epic.sojourner.common.model;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ActivityCategory {
  Impression, Click  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ActivityCategory\",\"namespace\":\"com.ebay.epic.sojourner.common.model\",\"symbols\":[\"Impression\",\"Click\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
